import type { PropertyDetail, Booking, PropertySummary } from './types';

export const allProperties: PropertyDetail[] = [
  {
    property_id: '1',
    name: 'Serene Downtown Apartment',
    description: 'A beautiful and quiet apartment in the heart of the city, perfect for a couple\'s getaway. Enjoy the stunning city views and modern amenities.',
    city: 'New York',
    state: 'NY',
    country: 'USA',
    postal_code: 10001,
    address: '123 Main St, New York, NY 10001',
    price_per_night: 250,
    imageList: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    hero_image_src: 'https://placehold.co/600x400.png',
    guests: 2,
    bedroom: 1,
    beds: 1,
    bathroom: 1,
    type: 'Apartment',
    rating: 4.9,
    reviewsCount: 120,
    hostname: 'Alice Johnson',
    host_avatar_src: 'https://placehold.co/100x100.png',
  },
  {
    property_id: '2',
    name: 'Cozy Beachfront Cottage',
    description: 'Wake up to the sound of waves in this charming beachfront cottage. Ideal for families or small groups looking for a relaxing vacation by the sea.',
    city: 'Malibu',
    state: 'CA',
    country: 'USA',
    postal_code: 90265,
    address: '456 Pacific Coast Hwy, Malibu, CA 90265',
    price_per_night: 400,
    imageList: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    hero_image_src: 'https://placehold.co/600x400.png',
    guests: 4,
    bedroom: 2,
    beds: 2,
    bathroom: 2,
    type: 'Cottage',
    rating: 4.8,
    reviewsCount: 85,
    hostname: 'Bob Williams',
    host_avatar_src: 'https://placehold.co/100x100.png',
  },
  {
    property_id: '3',
    name: 'Luxury Parisian Flat',
    description: 'Experience the magic of Paris from this elegant and centrally located flat. Close to major attractions, shops, and restaurants.',
    city: 'Paris',
    state: 'Île-de-France',
    country: 'France',
    postal_code: 75001,
    address: '7 Rue de Rivoli, 75001 Paris, France',
    price_per_night: 350,
    imageList: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    hero_image_src: 'https://placehold.co/600x400.png',
    guests: 3,
    bedroom: 1,
    beds: 2,
    bathroom: 1,
    type: 'Flat',
    rating: 4.9,
    reviewsCount: 200,
    hostname: 'Claire Dubois',
    host_avatar_src: 'https://placehold.co/100x100.png',
  },
  {
    property_id: '4',
    name: 'Modern Tokyo Studio',
    description: 'A sleek and stylish studio in a vibrant Tokyo neighborhood. Perfect for solo travelers or couples exploring the city.',
    city: 'Tokyo',
    state: 'Tokyo',
    country: 'Japan',
    postal_code: 1600022,
    address: '1-1-1 Shinjuku, Shinjuku City, Tokyo 160-0022',
    price_per_night: 180,
    imageList: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    hero_image_src: 'https://placehold.co/600x400.png',
    guests: 2,
    bedroom: 1,
    beds: 1,
    bathroom: 1,
    type: 'Studio',
    rating: 4.7,
    reviewsCount: 150,
    hostname: 'Ken Tanaka',
    host_avatar_src: 'https://placehold.co/100x100.png',
  },
  {
    property_id: '5',
    name: 'Mountain View Cabin',
    description: 'Escape to this luxurious cabin with breathtaking mountain views. Enjoy hiking, skiing, or simply relaxing by the fire.',
    city: 'Aspen',
    state: 'CO',
    country: 'USA',
    postal_code: 81611,
    address: '789 Mountain Rd, Aspen, CO 81611',
    price_per_night: 550,
    imageList: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    hero_image_src: 'https://placehold.co/600x400.png',
    guests: 6,
    bedroom: 3,
    beds: 4,
    bathroom: 3,
    type: 'Cabin',
    rating: 5.0,
    reviewsCount: 95,
    hostname: 'David Smith',
    host_avatar_src: 'https://placehold.co/100x100.png',
  },
  {
    property_id: '6',
    name: 'Historic London Townhouse',
    description: 'Stay in a piece of history in this beautifully restored townhouse. Located in a quiet, prestigious neighborhood with easy access to public transport.',
    city: 'London',
    state: 'England',
    country: 'UK',
    postal_code: 10101, // Mock data
    address: '10 Downing Street, London, UK',
    price_per_night: 320,
    imageList: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    hero_image_src: 'https://placehold.co/600x400.png',
    guests: 5,
    bedroom: 3,
    beds: 3,
    bathroom: 2,
    type: 'Townhouse',
    rating: 4.8,
    reviewsCount: 110,
    hostname: 'Emily Clark',
    host_avatar_src: 'https://placehold.co/100x100.png',
  },
];

export const myBookings: Booking[] = [
  {
    bookingId: 'booking-1',
    property: allProperties[2],
    checkIn: '2024-08-15',
    checkOut: '2024-08-20',
    guests: 2,
    totalPrice: 1750,
  },
  {
    bookingId: 'booking-2',
    property: allProperties[4],
    checkIn: '2024-09-10',
    checkOut: '2024-09-15',
    guests: 4,
    totalPrice: 2750,
  }
];
