import type { PropertyDetail, Booking } from './types';

// Let's pre-populate with some data for demonstration
export const allProperties: PropertyDetail[] = [
    {
        propertyId: 'prop1',
        name: 'Seaside Villa in Malibu',
        description: 'Experience luxury at this stunning seaside villa. With breathtaking ocean views, a private pool, and modern amenities, it\'s the perfect getaway for families or groups. Enjoy the spacious living areas and the serene beach at your doorstep.',
        city: 'Malibu',
        state: 'California',
        country: 'USA',
        postal_code: 90265,
        address: '123 Ocean Drive',
        price_per_night: 500,
        imageList: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
        hero_image_src: 'https://placehold.co/600x400.png',
        guests: 4,
        bedroom: 2,
        beds: 2,
        bathroom: 2,
        type: 'Villa',
        rating: 4.9,
        reviewsCount: 120,
        hostname: 'Sarah Host',
        host_avatar_src: 'https://placehold.co/100x100.png',
    },
    {
        propertyId: 'prop2',
        name: 'Chic Urban Loft',
        description: 'A stylish and modern loft located in the heart of New York. This space is perfect for couples or solo travelers looking to explore the city. It features an open-plan living area, a fully equipped kitchen, and easy access to public transport.',
        city: 'New York',
        state: 'New York',
        country: 'USA',
        postal_code: 10001,
        address: '456 High Line',
        price_per_night: 300,
        imageList: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
        hero_image_src: 'https://placehold.co/600x400.png',
        guests: 2,
        bedroom: 1,
        beds: 1,
        bathroom: 1,
        type: 'Loft',
        rating: 4.7,
        reviewsCount: 88,
        hostname: 'Sarah Host',
        host_avatar_src: 'https://placehold.co/100x100.png',
    },
    {
        propertyId: 'prop3',
        name: 'Cozy Mountain Cabin',
        description: 'Escape to this charming and cozy cabin in Aspen. Surrounded by nature, it offers a peaceful retreat with a rustic feel and all the modern comforts. Ideal for hiking in the summer and skiing in the winter.',
        city: 'Aspen',
        state: 'Colorado',
        country: 'USA',
        postal_code: 81611,
        address: '789 Pine Trail',
        price_per_night: 250,
        imageList: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
        hero_image_src: 'https://placehold.co/600x400.png',
        guests: 6,
        bedroom: 3,
        beds: 4,
        bathroom: 2,
        type: 'Cabin',
        rating: 4.8,
        reviewsCount: 200,
        hostname: 'John Doe',
        host_avatar_src: 'https://placehold.co/100x100.png',
    },
    {
        propertyId: 'prop4',
        name: 'Modern Downtown Apartment',
        description: 'A sleek and modern apartment in downtown Paris, offering stunning views of the city. Perfect for business travelers or tourists, with all major attractions just a short walk away. The apartment is fully furnished with high-end appliances.',
        city: 'Paris',
        state: 'Île-de-France',
        country: 'France',
        postal_code: 75001,
        address: '101 Rue de Rivoli',
        price_per_night: 400,
        imageList: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
        hero_image_src: 'https://placehold.co/600x400.png',
        guests: 3,
        bedroom: 2,
        beds: 2,
        bathroom: 1,
        type: 'Apartment',
        rating: 4.6,
        reviewsCount: 150,
        hostname: 'Sarah Host',
        host_avatar_src: 'https://placehold.co/100x100.png',
    }
];

export const myBookings: Booking[] = [];
