import type { Property } from './types';

export const allProperties: Property[] = [
  {
    id: '1',
    name: 'Serene Downtown Apartment',
    type: 'Apartment',
    city: 'New York',
    country: 'USA',
    heroImage: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    pricePerNight: 250,
    rating: 4.9,
    reviewsCount: 120,
    host: { name: 'Alice Johnson', avatar: 'https://placehold.co/100x100.png' },
    details: { guests: 2, bedrooms: 1, beds: 1, bathrooms: 1 },
    amenities: ['Wifi', 'Kitchen', 'Air Conditioning', 'TV'],
    description: 'A beautiful and quiet apartment in the heart of the city, perfect for a couple\'s getaway. Enjoy the stunning city views and modern amenities.'
  },
  {
    id: '2',
    name: 'Cozy Beachfront Cottage',
    type: 'Cottage',
    city: 'Malibu',
    country: 'USA',
    heroImage: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    pricePerNight: 400,
    rating: 4.8,
    reviewsCount: 85,
    host: { name: 'Bob Williams', avatar: 'https://placehold.co/100x100.png' },
    details: { guests: 4, bedrooms: 2, beds: 2, bathrooms: 2 },
    amenities: ['Wifi', 'Kitchen', 'Beach Access', 'Free Parking'],
    description: 'Wake up to the sound of waves in this charming beachfront cottage. Ideal for families or small groups looking for a relaxing vacation by the sea.'
  },
  {
    id: '3',
    name: 'Luxury Parisian Flat',
    type: 'Flat',
    city: 'Paris',
    country: 'France',
    heroImage: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    pricePerNight: 350,
    rating: 4.9,
    reviewsCount: 200,
    host: { name: 'Claire Dubois', avatar: 'https://placehold.co/100x100.png' },
    details: { guests: 3, bedrooms: 1, beds: 2, bathrooms: 1 },
    amenities: ['Wifi', 'Kitchen', 'Elevator', 'Washer'],
    description: 'Experience the magic of Paris from this elegant and centrally located flat. Close to major attractions, shops, and restaurants.'
  },
  {
    id: '4',
    name: 'Modern Tokyo Studio',
    type: 'Studio',
    city: 'Tokyo',
    country: 'Japan',
    heroImage: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    pricePerNight: 180,
    rating: 4.7,
    reviewsCount: 150,
    host: { name: 'Ken Tanaka', avatar: 'https://placehold.co/100x100.png' },
    details: { guests: 2, bedrooms: 1, beds: 1, bathrooms: 1 },
    amenities: ['Wifi', 'Kitchenette', 'Air Conditioning', 'Pocket Wifi'],
    description: 'A sleek and stylish studio in a vibrant Tokyo neighborhood. Perfect for solo travelers or couples exploring the city.'
  },
  {
    id: '5',
    name: 'Mountain View Cabin',
    type: 'Cabin',
    city: 'Aspen',
    country: 'USA',
    heroImage: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    pricePerNight: 550,
    rating: 5.0,
    reviewsCount: 95,
    host: { name: 'David Smith', avatar: 'https://placehold.co/100x100.png' },
    details: { guests: 6, bedrooms: 3, beds: 4, bathrooms: 3 },
    amenities: ['Wifi', 'Kitchen', 'Hot Tub', 'Fireplace'],
    description: 'Escape to this luxurious cabin with breathtaking mountain views. Enjoy hiking, skiing, or simply relaxing by the fire.'
  },
  {
    id: '6',
    name: 'Historic London Townhouse',
    type: 'Townhouse',
    city: 'London',
    country: 'UK',
    heroImage: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    pricePerNight: 320,
    rating: 4.8,
    reviewsCount: 110,
    host: { name: 'Emily Clark', avatar: 'https://placehold.co/100x100.png' },
    details: { guests: 5, bedrooms: 3, beds: 3, bathrooms: 2 },
    amenities: ['Wifi', 'Kitchen', 'Heating', 'Garden'],
    description: 'Stay in a piece of history in this beautifully restored townhouse. Located in a quiet, prestigious neighborhood with easy access to public transport.'
  },
];

export const featuredProperties = allProperties.slice(0, 4);
